"""
Module to display LNS parameter test results in a readable format.

Provides functions to load and visualize parameter optimization results
from JSON files generated by find_lns_parameter.py.
"""

import json
from pathlib import Path
from typing import Any


def format_duration(seconds: float) -> str:
    """Format duration in seconds to readable string."""
    if seconds < 60:
        return f"{seconds:.2f}s"
    elif seconds < 3600:
        minutes = int(seconds // 60)
        secs = seconds % 60
        return f"{minutes}m {secs:.2f}s"
    else:
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = seconds % 60
        return f"{hours}h {minutes}m {secs:.2f}s"


def format_parameter_value(key: str, value: Any) -> str:
    """Format parameter value for display."""
    if isinstance(value, float):
        if value < 1:
            return f"{value:.3f}"
        else:
            return f"{value:.2f}"
    return str(value)


def display_lns_results(
    json_file: Path | str, show_all_results: bool = False, top_n: int = 5
) -> None:
    """
    Display LNS parameter optimization results in a formatted way.

    Args:
        json_file: Path to the JSON results file
        show_all_results: If True, show all test results. If False, show only top N
        top_n: Number of top results to show (when show_all_results=False)
    """
    json_file = Path(json_file)

    if not json_file.exists():
        print(f"❌ File not found: {json_file}")
        return

    with open(json_file, "r") as f:
        data = json.load(f)

    # Header
    print("=" * 100)
    print("LNS PARAMETER OPTIMIZATION RESULTS".center(100))
    print("=" * 100)
    print()

    # Summary
    print(f"📊 Instance: {data['instance_name']}")
    print(f"🔢 Total configurations tested: {data['total_configurations_tested']}")
    print()

    # Best result
    if data.get("best_result"):
        best = data["best_result"]
        print("🏆 BEST CONFIGURATION".center(100, "="))
        print()
        print(f"  Run Index:        #{best['run_index']}")
        print(f"  Objective Value:  {best['objective_value']}")
        print(f"  Runtime:          {format_duration(best['runtime_seconds'])}")
        print(f"  Solve Status:     {best['solve_status']}")
        print(f"  Timestamp:        {best['timestamp']}")
        print()
        print("  Parameters:")
        for key, value in best["config"].items():
            formatted_value = format_parameter_value(key, value)
            print(f"    • {key:.<45} {formatted_value}")
        print()

    # All results
    if data.get("all_results"):
        all_results = sorted(data["all_results"], key=lambda x: x["objective_value"])

        if show_all_results:
            results_to_show = all_results
            title = "ALL TEST RESULTS (sorted by objective value)"
        else:
            results_to_show = all_results[:top_n]
            title = f"TOP {top_n} CONFIGURATIONS (by objective value)"

        print(title.center(100, "="))
        print()

        # Table header
        print(
            f"{'Rank':<6} {'Run#':<6} {'Objective':<12} {'Runtime':<12} "
            f"{'Win Size':<10} {'Inc Factor':<12} {'Dec Factor':<12} {'Threshold':<10}"
        )
        print("-" * 100)

        # Table rows
        for rank, result in enumerate(results_to_show, 1):
            config = result["config"]
            print(
                f"{rank:<6} "
                f"#{result['run_index']:<5} "
                f"{result['objective_value']:<12.1f} "
                f"{format_duration(result['runtime_seconds']):<12} "
                f"{config['start_search_window_size']:<10} "
                f"{config['window_increase_factor']:<12.2f} "
                f"{config['window_decrease_factor']:<12.2f} "
                f"{config['strong_improvement_threshold']:<10.3f}"
            )

        print()

        # Statistics
        print("📈 STATISTICS".center(100, "="))
        print()

        objectives = [r["objective_value"] for r in all_results]
        runtimes = [r["runtime_seconds"] for r in all_results]

        best_obj = min(objectives)
        worst_obj = max(objectives)
        avg_obj = sum(objectives) / len(objectives)

        avg_runtime = sum(runtimes) / len(runtimes)
        total_runtime = sum(runtimes)

        print("  Objective Values:")
        print(f"    Best:    {best_obj:.1f}")
        print(f"    Worst:   {worst_obj:.1f}")
        print(f"    Average: {avg_obj:.1f}")
        print(f"    Range:   {worst_obj - best_obj:.1f}")
        print()
        print("  Runtimes:")
        print(f"    Average: {format_duration(avg_runtime)}")
        print(f"    Total:   {format_duration(total_runtime)}")
        print()

    print("=" * 100)


def compare_configurations(json_file: Path | str, run_indices: list[int]) -> None:
    """
    Compare specific configurations side by side.

    Args:
        json_file: Path to the JSON results file
        run_indices: List of run indices to compare
    """
    json_file = Path(json_file)

    if not json_file.exists():
        print(f"❌ File not found: {json_file}")
        return

    with open(json_file, "r") as f:
        data = json.load(f)

    all_results = {r["run_index"]: r for r in data.get("all_results", [])}

    # Filter requested results
    results_to_compare = []
    for idx in run_indices:
        if idx in all_results:
            results_to_compare.append(all_results[idx])
        else:
            print(f"⚠️  Run #{idx} not found in results")

    if not results_to_compare:
        print("❌ No valid runs to compare")
        return

    print("=" * 100)
    print(f"COMPARING {len(results_to_compare)} CONFIGURATIONS".center(100))
    print("=" * 100)
    print()

    # Comparison table
    print(f"{'Metric':<40}", end="")
    for result in results_to_compare:
        print(f"  Run #{result['run_index']:<15}", end="")
    print()
    print("-" * 100)

    # Objective values
    print(f"{'Objective Value':<40}", end="")
    for result in results_to_compare:
        print(f"  {result['objective_value']:<15.1f}", end="")
    print()

    # Runtimes
    print(f"{'Runtime':<40}", end="")
    for result in results_to_compare:
        print(f"  {format_duration(result['runtime_seconds']):<15}", end="")
    print()

    print()

    # Parameters
    print("Parameters:")
    print("-" * 100)

    # Get all parameter keys
    param_keys = list(results_to_compare[0]["config"].keys())

    for key in param_keys:
        print(f"  {key:<38}", end="")
        for result in results_to_compare:
            value = result["config"][key]
            formatted = format_parameter_value(key, value)
            print(f"  {formatted:<15}", end="")
        print()

    print()
    print("=" * 100)


def main():
    """Example usage of the display functions."""
    # Path to results file
    results_file = (
        Path(__file__).parent.parent.parent / "data" / "lns_parameter_results.json"
    )

    # Display all results
    print("\n")
    display_lns_results(results_file, show_all_results=False, top_n=10)

    # Compare specific configurations
    print("\n\n")
    compare_configurations(results_file, run_indices=[1, 2, 3])


if __name__ == "__main__":
    main()
