"""
Module to display LNS parameter test results in a readable format.

Provides functions to load and visualize parameter optimization results
from JSON files generated by find_lns_parameter.py.
"""

import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional


@dataclass
class ResultSummary:
    """Summary of a single test result"""

    run_id: int
    instance_name: str
    objective_value: float
    solve_status: str
    runtime_seconds: float
    parameters: dict
    log_file: str

    @staticmethod
    def from_dict(data: dict) -> "ResultSummary":
        """Create ResultSummary from dict"""
        return ResultSummary(
            run_id=data["run_id"],
            instance_name=data["instance_name"],
            objective_value=data["objective_value"],
            solve_status=data["solve_status"],
            runtime_seconds=data["runtime_seconds"],
            parameters=data["parameters"],
            log_file=data.get("log_file", ""),
        )


class ResultAnalyzer:
    """Analyzer for LNS parameter test results"""

    def __init__(self, base_dir: Path):
        self.base_dir = Path(base_dir)
        self.results: list[ResultSummary] = []

    def load_all_results(self):
        """Load all results from the base directory"""
        self.results = []

        if not self.base_dir.exists():
            print(f"Directory {self.base_dir} does not exist")
            return

        # Find all batch directories
        batch_dirs = sorted([d for d in self.base_dir.iterdir() if d.is_dir()])

        for batch_dir in batch_dirs:
            # Find all result files in this batch (result_run_0.json, result_run_1.json, etc.)
            result_files = sorted(batch_dir.glob("result_run_*.json"))

            for result_file in result_files:
                try:
                    with open(result_file, "r") as f:
                        data = json.load(f)
                        self.results.append(ResultSummary.from_dict(data))
                except Exception as e:
                    print(f"Error loading {result_file}: {e}")

        print(f"Loaded {len(self.results)} results from {len(batch_dirs)} batches")

    def get_results_by_instance(self, instance_name: str) -> list[ResultSummary]:
        """Get all results for a specific instance"""
        return [r for r in self.results if r.instance_name == instance_name]

    def get_best_result_by_instance(
        self, instance_name: str
    ) -> Optional[ResultSummary]:
        """Get the best result for a specific instance"""
        instance_results = self.get_results_by_instance(instance_name)
        if not instance_results:
            return None
        return min(instance_results, key=lambda r: r.objective_value)

    def get_best_parameters_by_instance(self, instance_name: str) -> Optional[dict]:
        """Get the best parameters for a specific instance"""
        best_result = self.get_best_result_by_instance(instance_name)
        if best_result:
            return best_result.parameters
        return None

    def get_all_instances(self) -> list[str]:
        """Get list of all tested instances"""
        return sorted(set(r.instance_name for r in self.results))

    def print_summary(self):
        """Print a summary of all results"""
        if not self.results:
            print("No results loaded")
            return

        print("\n" + "=" * 80)
        print("LNS PARAMETER TEST RESULTS SUMMARY")
        print("=" * 80)

        instances = self.get_all_instances()

        for instance_name in instances:
            print(f"\n{instance_name}:")
            print("-" * 40)

            instance_results = self.get_results_by_instance(instance_name)
            best_result = min(instance_results, key=lambda r: r.objective_value)

            print(f"  Total runs: {len(instance_results)}")
            print(f"  Best objective: {best_result.objective_value}")
            print(f"  Best runtime: {best_result.runtime_seconds:.2f}s")
            print("  Best parameters:")
            for key, value in best_result.parameters.items():
                print(f"    - {key}: {value}")

        print("\n" + "=" * 80)

    def compare_parameter(
        self, parameter_name: str, instance_name: Optional[str] = None
    ):
        """
        Compare results for different values of a specific parameter

        Args:
            parameter_name: Name of the parameter to compare
            instance_name: Optional instance name to filter by
        """
        results = self.results
        if instance_name:
            results = self.get_results_by_instance(instance_name)

        if not results:
            print("No results to compare")
            return

        # Group by parameter value
        grouped = defaultdict(list)

        for result in results:
            if parameter_name in result.parameters:
                param_value = result.parameters[parameter_name]
                grouped[param_value].append(result)

        print(f"\n{'=' * 80}")
        print(f"PARAMETER COMPARISON: {parameter_name}")
        if instance_name:
            print(f"Instance: {instance_name}")
        print("=" * 80)

        for param_value in sorted(grouped.keys()):
            results_for_value = grouped[param_value]
            avg_objective = sum(r.objective_value for r in results_for_value) / len(
                results_for_value
            )
            avg_runtime = sum(r.runtime_seconds for r in results_for_value) / len(
                results_for_value
            )
            best_objective = min(r.objective_value for r in results_for_value)

            print(f"\n{parameter_name} = {param_value}:")
            print(f"  Runs: {len(results_for_value)}")
            print(f"  Avg objective: {avg_objective:.2f}")
            print(f"  Best objective: {best_objective:.2f}")
            print(f"  Avg runtime: {avg_runtime:.2f}s")

        print("\n" + "=" * 80)

    def export_to_csv(self, output_file: Path):
        """Export all results to CSV file"""
        import csv

        if not self.results:
            print("No results to export")
            return

        with open(output_file, "w", newline="") as f:
            # Get all parameter names
            all_param_names = set()
            for result in self.results:
                all_param_names.update(result.parameters.keys())
            param_names = sorted(all_param_names)

            fieldnames = [
                "run_id",
                "instance_name",
                "objective_value",
                "solve_status",
                "runtime_seconds",
            ] + param_names

            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()

            for result in self.results:
                row = {
                    "run_id": result.run_id,
                    "instance_name": result.instance_name,
                    "objective_value": result.objective_value,
                    "solve_status": result.solve_status,
                    "runtime_seconds": result.runtime_seconds,
                }
                for param_name in param_names:
                    row[param_name] = result.parameters.get(param_name, "")
                writer.writerow(row)

        print(f"Results exported to {output_file}")


def format_duration(seconds: float) -> str:
    """Format duration in seconds to readable string."""
    if seconds < 60:
        return f"{seconds:.2f}s"
    elif seconds < 3600:
        minutes = int(seconds // 60)
        secs = seconds % 60
        return f"{minutes}m {secs:.2f}s"
    else:
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = seconds % 60
        return f"{hours}h {minutes}m {secs:.2f}s"


def format_parameter_value(key: str, value: Any) -> str:
    """Format parameter value for display."""
    if isinstance(value, float):
        if value < 1:
            return f"{value:.3f}"
        else:
            return f"{value:.2f}"
    return str(value)


def display_lns_results(
    json_file: Path | str, show_all_results: bool = False, top_n: int = 5
) -> None:
    """
    Display LNS parameter optimization results in a formatted way.

    Args:
        json_file: Path to the JSON results file
        show_all_results: If True, show all test results. If False, show only top N
        top_n: Number of top results to show (when show_all_results=False)
    """
    json_file = Path(json_file)

    if not json_file.exists():
        print(f"❌ File not found: {json_file}")
        return

    with open(json_file, "r") as f:
        data = json.load(f)

    # Header
    print("=" * 100)
    print("LNS PARAMETER OPTIMIZATION RESULTS".center(100))
    print("=" * 100)
    print()

    # Summary
    print(f"📊 Instance: {data['instance_name']}")
    print(f"🔢 Total configurations tested: {data['total_configurations_tested']}")
    print()

    # Best result
    if data.get("best_result"):
        best = data["best_result"]
        print("🏆 BEST CONFIGURATION".center(100, "="))
        print()
        print(f"  Run Index:        #{best['run_index']}")
        print(f"  Objective Value:  {best['objective_value']}")
        print(f"  Runtime:          {format_duration(best['runtime_seconds'])}")
        print(f"  Solve Status:     {best['solve_status']}")
        print(f"  Timestamp:        {best['timestamp']}")
        print()
        print("  Parameters:")
        for key, value in best["config"].items():
            formatted_value = format_parameter_value(key, value)
            print(f"    • {key:.<45} {formatted_value}")
        print()

    # All results
    if data.get("all_results"):
        all_results = sorted(data["all_results"], key=lambda x: x["objective_value"])

        if show_all_results:
            results_to_show = all_results
            title = "ALL TEST RESULTS (sorted by objective value)"
        else:
            results_to_show = all_results[:top_n]
            title = f"TOP {top_n} CONFIGURATIONS (by objective value)"

        print(title.center(100, "="))
        print()

        # Table header
        print(
            f"{'Rank':<6} {'Run#':<6} {'Objective':<12} {'Runtime':<12} "
            f"{'Win Size':<10} {'Inc Factor':<12} {'Dec Factor':<12} {'Threshold':<10}"
        )
        print("-" * 100)

        # Table rows
        for rank, result in enumerate(results_to_show, 1):
            config = result["config"]
            print(
                f"{rank:<6} "
                f"#{result['run_index']:<5} "
                f"{result['objective_value']:<12.1f} "
                f"{format_duration(result['runtime_seconds']):<12} "
                f"{config['start_search_window_size']:<10} "
                f"{config['window_increase_factor']:<12.2f} "
                f"{config['window_decrease_factor']:<12.2f} "
                f"{config['strong_improvement_threshold']:<10.3f}"
            )

        print()

        # Statistics
        print("📈 STATISTICS".center(100, "="))
        print()

        objectives = [r["objective_value"] for r in all_results]
        runtimes = [r["runtime_seconds"] for r in all_results]

        best_obj = min(objectives)
        worst_obj = max(objectives)
        avg_obj = sum(objectives) / len(objectives)

        avg_runtime = sum(runtimes) / len(runtimes)
        total_runtime = sum(runtimes)

        print("  Objective Values:")
        print(f"    Best:    {best_obj:.1f}")
        print(f"    Worst:   {worst_obj:.1f}")
        print(f"    Average: {avg_obj:.1f}")
        print(f"    Range:   {worst_obj - best_obj:.1f}")
        print()
        print("  Runtimes:")
        print(f"    Average: {format_duration(avg_runtime)}")
        print(f"    Total:   {format_duration(total_runtime)}")
        print()

    print("=" * 100)


def compare_configurations(json_file: Path | str, run_indices: list[int]) -> None:
    """
    Compare specific configurations side by side.

    Args:
        json_file: Path to the JSON results file
        run_indices: List of run indices to compare
    """
    json_file = Path(json_file)

    if not json_file.exists():
        print(f"❌ File not found: {json_file}")
        return

    with open(json_file, "r") as f:
        data = json.load(f)

    all_results = {r["run_index"]: r for r in data.get("all_results", [])}

    # Filter requested results
    results_to_compare = []
    for idx in run_indices:
        if idx in all_results:
            results_to_compare.append(all_results[idx])
        else:
            print(f"⚠️  Run #{idx} not found in results")

    if not results_to_compare:
        print("❌ No valid runs to compare")
        return

    print("=" * 100)
    print(f"COMPARING {len(results_to_compare)} CONFIGURATIONS".center(100))
    print("=" * 100)
    print()

    # Comparison table
    print(f"{'Metric':<40}", end="")
    for result in results_to_compare:
        print(f"  Run #{result['run_index']:<15}", end="")
    print()
    print("-" * 100)

    # Objective values
    print(f"{'Objective Value':<40}", end="")
    for result in results_to_compare:
        print(f"  {result['objective_value']:<15.1f}", end="")
    print()

    # Runtimes
    print(f"{'Runtime':<40}", end="")
    for result in results_to_compare:
        print(f"  {format_duration(result['runtime_seconds']):<15}", end="")
    print()

    print()

    # Parameters
    print("Parameters:")
    print("-" * 100)

    # Get all parameter keys
    param_keys = list(results_to_compare[0]["config"].keys())

    for key in param_keys:
        print(f"  {key:<38}", end="")
        for result in results_to_compare:
            value = result["config"][key]
            formatted = format_parameter_value(key, value)
            print(f"  {formatted:<15}", end="")
        print()

    print()
    print("=" * 100)


def main():
    """Example usage of the display and analyzer functions."""

    # Option 1: Analyze results from test runs (new format)
    print("\n=== Analyzing test run results ===\n")
    analyzer = ResultAnalyzer(Path("lns_parameter_tests"))
    analyzer.load_all_results()
    analyzer.print_summary()

    # Compare specific parameter
    # analyzer.compare_parameter("start_search_window_size", "Instance1")

    # Export to CSV
    # analyzer.export_to_csv(Path("lns_results.csv"))

    # Option 2: Display old format results (legacy)
    # results_file = (
    #     Path(__file__).parent.parent.parent / "data" / "lns_parameter_results.json"
    # )
    # display_lns_results(results_file, show_all_results=False, top_n=10)
    # compare_configurations(results_file, run_indices=[1, 2, 3])


if __name__ == "__main__":
    main()
